version: '3'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
